#!/bin/sh

echo $ART_INC > .kdev_include_paths
echo $LARSIM_INC >> .kdev_include_paths
echo $LARDATA_INC >> .kdev_include_paths
echo $BOOST_INC >> .kdev_include_paths
echo $LAREXAMPLES_INC >> .kdev_include_paths
echo $NUTOOLS_INC >> .kdev_include_paths
echo $LHAPDF_INC >> .kdev_include_paths
echo $UBOONEDAQ_DATATYPES_INC >> .kdev_include_paths
echo $XROOTD_INC >> .kdev_include_paths
echo $FFTW_INC >> .kdev_include_paths
echo $CETLIB_INC >> .kdev_include_paths
echo $LARRECO_INC >> .kdev_include_paths
echo $TBB_INC >> .kdev_include_paths
echo $POSTGRESQL_INCLUDE_DIR >> .kdev_include_paths
echo $GENIE_INC >> .kdev_include_paths
echo $LAREVENTDISPLAY_INC >> .kdev_include_paths
echo $LARPANDORA_INC >> .kdev_include_paths
echo $GSL_INC >> .kdev_include_paths
echo $MESSAGEFACILITY_INC >> .kdev_include_paths
echo $PANDORA_INC >> .kdev_include_paths
echo $FHICLCPP_INC >> .kdev_include_paths
echo $LAREVT_INC >> .kdev_include_paths
echo $LARSIM_INC >> .kdev_include_paths
echo $LIBWDA_INC >> .kdev_include_paths
echo $FFTW_INCLUDE_DIR >> .kdev_include_paths
echo $UBOONECODE_INC >> .kdev_include_paths
echo $CPPUNIT_INC >> .kdev_include_paths
echo $CPP0X_INC >> .kdev_include_paths
echo $XERCES_C_INC >> .kdev_include_paths
echo $LIBXML2_INC >> .kdev_include_paths
echo $MYSQL_CLIENT_INC >> .kdev_include_paths
echo $LARCORE_INC >> .kdev_include_paths
echo $LARPANDORACONTENT_INC >> .kdev_include_paths
echo $CLHEP_INCLUDE_DIR >> .kdev_include_paths
echo $ARTEXTENSIONS_INC >> .kdev_include_paths
echo $LOG4CPP_INC >> .kdev_include_paths
echo $ART_INC >> .kdev_include_paths
echo $CLHEP_INC >> .kdev_include_paths
echo $POSTGRESQL_INC >> .kdev_include_paths
echo $SQLITE_INC >> .kdev_include_paths
echo $LARANA_INC >> .kdev_include_paths
echo $LARDATA_INC >> .kdev_include_paths
echo $ROOT_INC >> .kdev_include_paths
echo $IFDH_ART_INC >> .kdev_include_paths
echo $PYTHIA_INC >> .kdev_include_paths
echo $PYTHON_INCLUDE >> .kdev_include_paths
echo $MRB_SOURCE/laserana >> .kdev_include_paths
